services:
  - type: web
    name: aqillah
    env: node
    buildCommand: npm install && npm run db:generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_AQILLAH_MAPS_WEB_KEY
        sync: false
      - key: AQILLAH_MAPS_WEB_KEY
        sync: false
      - key: AQILLAH_ROUTES_KEY
        sync: false
      - key: AQILLAH_PLACES_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false

